<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_bot">

  <!-- ====== Parameters ====== -->
  <xacro:property name="base_length" value="0.40"/>
  <xacro:property name="base_width"  value="0.28"/>
  <xacro:property name="base_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="wheel_width"  value="0.03"/>
  <xacro:property name="wheel_separation" value="0.22"/> <!-- distance between wheel centers -->

  <xacro:property name="base_mass" value="5.0"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <!-- ====== Materials ====== -->
  <material name="gray"><color rgba="0.6 0.6 0.6 1"/></material>
  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>

  <!-- ====== Links ====== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <!-- simple box inertia approximation -->
      <inertia
        ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}"
        iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}"
        izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- ====== Joints ====== -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_separation/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ====== ros2_control (what diff_drive_controller talks to) ====== -->
  <ros2_control name="MyBotSystem" type="system">
    <hardware>
      <!-- Gazebo plugin will simulate this hardware -->
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>

    <joint name="right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>

  <!-- ====== Gazebo plugin hook for ros2_control ====== -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <!-- controller_manager reads robot_description -->
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
    </plugin>
  </gazebo>

</robot>
